// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// GetUserListResponse defines model for GetUserListResponse.
type GetUserListResponse = []struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
